name: Test

on: push

jobs:
  test:
    strategy:
      matrix:
        node-version: [16, 18, latest]
        runner: [ubuntu-22.04, windows-2022]

    name: Run tests
    runs-on: ${{ matrix.runner }}
    continue-on-error: true

    env:
      test-results-path: test-results.json

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm run test:ci -- output=${{ env.test-results-path }}

    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: '!cancelled()'
      with:
        name: Test results (${{ matrix.node-version }}, ${{ matrix.runner }})
        fail-on-error: false
        path: ${{ env.test-results-path }}
        reporter: mocha-json
