name: Test and publish

on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18, latest]
        runner: [ubuntu-22.04, windows-2022]

    name: Run tests
    runs-on: ${{ matrix.runner }}

    env:
      test-results-path: test-results.json

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Install node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm run test:ci -- output=${{ env.test-results-path }}

    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: '!cancelled()'
      with:
        name: Test results (${{ matrix.node-version }}, ${{ matrix.runner }})
        fail-on-error: false
        path: ${{ env.test-results-path }}
        reporter: mocha-json

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    name: Publish

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install node.js
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"

    - name: Install dependencies
      run: npm ci

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
