name: Test

on: push

jobs:
  test:
    strategy:
      matrix:
        node-version: [16, 18, latest]
        runner: [ubuntu-22.04, windows-2022]

    name: Run tests
    runs-on: ${{ matrix.runner }}
    continue-on-error: true
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm test
